### ISSUE TITLE
dose it work on gh-pages?

### ISSUE THREAD

**Issue by wdyggh** [toshimaru/jekyll-tagging-related_posts#5]
Hello toshimaru

I'm using plugin in my laptop environment and it  works well.
But i push my code on github, it doesn't work.
It shows the lasted post.Here is [my _config.yml](https://github.com/wdyggh/wdyggh.github.io/blob/master/_config.yml)

Thank you!

**Comment by toshimaru** [comment]
Hi, seems you're using official Github Pages where available plugin is limited.

https://pages.github.com/versions/

The solution is customizing pages using gh-pages brach. the detail is here 

https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

**Comment by wdyggh** [comment]
Thank you very much.
